name: Detect
on:
    workflow_dispatch:
    schedule:
        -   cron: '*/10 * * * *'

jobs:
    fetch:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Run script
                id: exec-script
                run: |
                    node scripts/detect.js

            -   name: Setup GitHub
                if: ${{ steps.exec-script.outputs.new_file }}
                run: |
                    git config user.name github-actions
                    git config user.email github-actions@github.com

            -   name: Submit data
                if: ${{ steps.exec-script.outputs.new_file }}
                run: |
                    git add .
                    git commit -m 'add new data'
#                    git push
        outputs:
            data: ${{ steps.exec-script.outputs.data }}

    notify:
        needs: [ fetch ]
        if: toJSON(needs.fetch.outputs.data) != '[]'
        uses: ./.github/workflows/notify.yml
        with:
            msg: ${{ needs.fetch.outputs.data }}
        secrets:
            notify_server: ${{ secrets.notify_server }}
            notify_token: ${{ secrets.notify_token }}
